# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-18 08:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='If editing the name of existing template, you must also update any code that uses it!', max_length=30)),
                ('subject', models.CharField(help_text='Please refer to the code to determine the context available', max_length=30)),
                ('body', ckeditor.fields.RichTextField(help_text='Please refer to the code to determine the context available')),
            ],
        ),
    ]
