# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
