# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_requested_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requested_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address'),
        ),
    ]
