# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration',
            field=models.CharField(default='AAA111', max_length=6),
            preserve_default=False,
        ),
    ]
