# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0004_vehicletype_daily_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
