# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0007_auto_20170928_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule_end',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule_start',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
