# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0008_auto_20170928_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='carshare.Booking'),
        ),
    ]
