# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshare', '0010_auto_20171020_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ended',
        ),
    ]
